version: '3.8'

services:
  book-recommender-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports: 
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - API_KEY=your-secret-api-key
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
