version: '3.8'

services:
  data-retrieval:
    build:
      context: .
      dockerfile: docker/data-retrieval/Dockerfile
    container_name: data-retrieval-container
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: ["keep-alive"]  # Keeps container running
    healthcheck:
      test: ["CMD", "test", "-f", "/app/data/raw/retrieval_complete"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  data-ingestion:
    build:
      context: .
      dockerfile: docker/data-ingestion/Dockerfile
    container_name: data-ingestion-container
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: ["keep-alive"]
    depends_on:
      data-retrieval:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/app/data/ingestion_complete"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  model-training:
    build:
      context: .
      dockerfile: docker/model-training/Dockerfile
    container_name: model-training-container
    environment:
      - PYTHONUNBUFFERED=1
      - GIT_PYTHON_GIT_EXECUTABLE=/usr/bin/git
      - GIT_PYTHON_REFRESH=quiet
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./src:/app/src
      - ./.git:/app/.git
      - ./config:/app/config

    depends_on:
      data-ingestion:
        condition: service_healthy
    command: ["keep-alive"]
    healthcheck:
      test: ["CMD", "test", "-f", "/app/models/collaborative.pkl"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  dvc:
    build:
      context: .
      dockerfile: docker/dvc/Dockerfile
    container_name: dvc-container
    environment:
      - PYTHONUNBUFFERED=1
      - GIT_USER_NAME=pepperumo
      - GIT_USER_EMAIL=pepperumo@gmail.com
      - GIT_BRANCH=dev
      - GIT_REMOTE_URL=git@github.com:pepperumo/MLOps_book_recommender_system.git     
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SKIP_GIT_PUSH=true
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./.git:/app/.git
      - ./.dvc:/app/.dvc
      - ./dvc.yaml:/app/dvc.yaml
      - ./dvc.lock:/app/dvc.lock
    depends_on:
      model-training:
        condition: service_healthy
    command: ["keep-alive"]
    healthcheck:
      test: ["CMD", "test", "-f", "/app/logs/dvc_complete"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  default:
    driver: bridge
