version: '3.8'

services:
  data-ingestion:
    build:
      context: .
      dockerfile: docker/data-ingestion/Dockerfile
    volumes:
      - ./data:/app/data
    networks:
      - recommender-network
    environment:
      - PYTHONUNBUFFERED=1
    command: ["keep-alive"]  # Keep container running
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/data/ingestion_complete || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  model-training:
    build:
      context: .
      dockerfile: docker/model-training/Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - recommender-network
    depends_on:
      data-ingestion:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    command: ["keep-alive"]  # Keep container running
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/models/training_complete || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  prediction-api:
    build:
      context: .
      dockerfile: docker/prediction-api/Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    ports:
      - "8000:8000"
    networks:
      - recommender-network
    depends_on:
      model-training:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1

networks:
  recommender-network:
    driver: bridge
