version: '3.8'

networks:  # Define network so all containers are connected
  goodreads_recommender_system
    driver: bridge

volumes: # this is done automatically somehow or we use   - /path/on/host:/path/in/container
  dvc_data:          # Persistent DVC cache and config - dvc_data:/dvc
  airflow_data:      # Airflow logs, config, and state
  bentoml_models:    # BentoML model store
  streamlit_data:    # Streamlit persistent data
  zenml_data:        # ZenML metadata store
  postgres_data:     # Database files
  shared_data:       # Cross-container shared files

services:
  # PostgreSQL for shared database needs
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=good_reads_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Database files
    networks:
      - goodreads_recommender_system
    ports:
      - "5432:5432"

  # DVC for version control of data
  dvc:
    image: dvcorg/dvc:latest
    volumes:
      - dvc_data:/dvc                         # DVC internal storage
      - ./project:/project                    # Project code and data
      - ./shared_data:/shared_data            # Shared data across containers
      - ./.dvc:/project/.dvc                  # DVC config and metadata
      - ./.git:/project/.git                  # Git repository
    working_dir: /project
    networks:
      - goodreads_recommender_system
    command: ["tail", "-f", "/dev/null"]      # Keep container running

  # Airflow for workflow orchestration
  airflow-webserver:
    image: apache/airflow:2.6.0
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://datauser:datapass@postgres/good_reads_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - airflow_data:/opt/airflow             # Airflow home directory
      - ./dags:/opt/airflow/dags              # DAG definitions
      - ./plugins:/opt/airflow/plugins        # Airflow plugins
      - ./shared_data:/shared_data            # Shared data across containers
      - ./logs:/opt/airflow/logs              # Airflow logs
    networks:
      - goodreads_recommender_system
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.6.0
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://datauser:datapass@postgres/good_reads_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - airflow_data:/opt/airflow             # Airflow home directory
      - ./dags:/opt/airflow/dags              # DAG definitions
      - ./plugins:/opt/airflow/plugins        # Airflow plugins
      - ./shared_data:/shared_data            # Shared data across containers
      - ./logs:/opt/airflow/logs              # Airflow logs
    networks:
      - goodreads_recommender_system
    command: scheduler

  # BentoML for model serving
  bentoml:
    image: bentoml/bentoml:latest
    volumes:
      - bentoml_models:/bentoml               # BentoML model store
      - ./models:/models                      # Additional model directory
      - ./shared_data:/shared_data            # Shared data across containers
      - ./bentoml_project:/bentoml_project    # BentoML project files
    networks:
      - goodreads_recommender_system
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - BENTOML_HOME=/bentoml

  # Streamlit for data visualization dashboards
  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    volumes:
      - streamlit_data:/app/data              # Persistent data for Streamlit
      - ./streamlit/app:/app                  # Streamlit application code
      - ./shared_data:/shared_data            # Shared data across containers
      - ./credentials:/app/credentials        # Credentials for APIs, etc.
    networks:
      - goodreads_recommender_system
    ports:
      - "8501:8501"
    command: streamlit run /app/main.py

  # ZenML for MLOps
  zenml:
    image: maiot/zenml:latest
    volumes:
      - zenml_data:/zenml                     # ZenML metadata store
      - ./pipelines:/pipelines                # ML pipeline definitions
      - ./shared_data:/shared_data            # Shared data across containers
      - ./zenml_config:/zenml_config          # ZenML configuration
    networks:
      - goodreads_recommender_system
    ports:
      - "8080:8080"
    environment:
      - ZENML_ANALYTICS_OPT_IN=false
      - ZENML_SERVER_DEFAULT_USERNAME=admin
      - ZENML_SERVER_DEFAULT_PASSWORD=password
