# Book Recommender System DVC Pipeline

stages:
  retrieve_data:
    cmd: python src/data/retrieve_raw_data.py
    deps:
      - src/data/retrieve_raw_data.py
    
  process_data:
    cmd: python src/data/process_data.py
    deps:
      - src/data/process_data.py
      - data
    
  build_features:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - data
    
  train_model:
    cmd: python src/models/train_model.py --config config/model_params.yaml
    deps:
      - src/models/train_model.py
      - config/model_params.yaml
      - data
    outs:
      - models/collaborative.pkl
      
  evaluate_model:
    cmd: python src/models/evaluate_model.py --model-path models/collaborative.pkl
    deps:
      - src/models/evaluate_model.py
      - models/collaborative.pkl
      - data
