# Book Recommender System DVC Pipeline

stages:
  retrieve_data:
    cmd: python src/data/retrieve_raw_data.py
    deps:
      - src/data/retrieve_raw_data.py
    outs:
      - data/raw:
          persist: true
      - data/backup:
          persist: true
      
  process_data:
    cmd: python src/data/process_data.py
    deps:
      - src/data/process_data.py
      - data/raw
    outs:
      - data/processed/merged_train.csv:
          persist: true
      - data/processed/merged_test.csv:
          persist: true
      - data/processed/books.csv:
          persist: true
      
  build_features:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - data/processed/merged_train.csv
      - data/processed/books.csv
    outs:
      - data/features/user_item_matrix.npz:
          persist: true
      - data/features/book_ids.npy:
          persist: true
      
  train_model:
    cmd: python src/models/train_model.py --config config/model_params.yaml
    deps:
      - src/models/train_model.py
      - config/model_params.yaml
      - data/features/user_item_matrix.npz
      - data/features/book_ids.npy
    outs:
      - models/collaborative.pkl:
          persist: true
      
  evaluate_model:
    cmd: python src/models/evaluate_model.py --model-path models/collaborative.pkl
    deps:
      - src/models/evaluate_model.py
      - models/collaborative.pkl
      - data/processed/merged_test.csv
    metrics:
      - data/results/evaluation_results.csv:
          cache: false