{
 "title": "Book_recommender_system",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Precision@k",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "book_recommender_precision", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recommendation Count by Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(book_recommendations_total) by (endpoint, status)",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Model Load Time",
   "type": "gauge",
   "description": "How fast the model loads",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_loading_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "95th Percentile Recommendation Time",
   "type": "timeseries",
   "description": "time to get a recommendation",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(recommendation_generation_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Recall@k",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    { "expr": "book_recommender_recall", "legendFormat": "__auto" }
   ]
  }
 ]
}