name: MLOps Book Recommender CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed for DVC to access history
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install flake8 pytest pytest-cov
    
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
    
    - name: Configure remote DVC storage
      run: |
        dvc pull -v || echo "DVC pull failed - continuing without data"
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run unit tests
      run: |
        pytest src/tests/ --cov=src/
    
    - name: Validate DVC pipeline
      run: |
        # Verify that process_data.py is correctly referenced in DVC pipeline
        ! grep -q "make_dataset.py" dvc.yaml
        grep -q "process_data.py" dvc.yaml || echo "Warning: process_data.py not found in DVC pipeline"
        
        # Validate DVC pipeline structure
        dvc dag

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
      
    - name: Run DVC repro to verify pipeline
      run: |
        dvc repro --dry